---
blank_issues_enabled: false
contact_links:
  - name: "💬 MyJournal.Notebook Discussions"
    url: https://github.com/atrenton/MyJournal.Notebook/discussions
    about: Chat with the developer and MyJournal.Notebook user community
  - name: "🚩 MyJournal.Notebook Known Issues"
    url: https://github.com/atrenton/MyJournal.Notebook/blob/master/docs/known-issues.md
    about: Known Issues for the MyJournal.Notebook OneNote Add-In
  - name: "📖 MyJournal.Notebook Wiki"
    url: https://github.com/atrenton/MyJournal.Notebook/wiki
    about: Documentation for users of the MyJournal.Notebook OneNote Add-In
...
