---
name: "💡 Feature request"
description: Suggest an idea for this project.
title: "[Feature request]: "
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Describe the feature you want
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## :point_right: Please limit one request per issue."
...
